spring:
  application:
    name: open-store
  datasource:
    url: jdbc:mysql://localhost:3306/open_store_db
    username: root
    password: 1224
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  security:
    user:
      name: none
      password: none
server:
  port: 8083
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG

image:
  upload:
    dir: "/media/user/Новый том/Images"